### ISSUE TITLE
Is there any plan to support load balance?

### ISSUE THREAD

**Issue by yuzhigang33** [Leanty/tree-gateway#11]
If the backend apis are in a cluster, does the gateway plan to add the feature of load balance ?

**Comment by thiagobustamante** [comment]
Yes. We are open to receiving feedback from the community in order to prioritize features. But, in any case, load balance and an integration with service discovery mechanisms are two items that we consider very important and should be available soon.

**Comment by yuzhigang33** [comment]
BTW，do you consider the data persistence ？ I think the data of apis/stats/monitors and so on should be persistent, not in redis.

**Comment by thiagobustamante** [comment]
At the moment we only support redis. But we can support others in the future, according to community feedbacks, for some kind of data, like apis configurations and stats. 

Other kinds of data, like cache entrances, circuitbreaker states, throttling counters etc, does not makes sense to be persisted in other database, because of the performance and because of the nature of the data. If some data is lost, it is not a big problem, they are all temporary data.

But I agree that API configurations and statistics could be stored in a database like mongodb to avoid the risk of loose some data. 

Redis was chosen because of the performance. We want to add the minimum overhead possible to the request pipeline. Using redis, we can perform, for example, any statistics writing with a single operation in a memory map. The overhead for this is not significant. If we use any other database, like mongo this time increases in a order of magnitude.

And we think that redis can provide to us a level of persistence that satisfies our use cases. 
It is possible to use redis clusters or sentinels to give some redundancy to our data.

**Comment by thiagobustamante** [comment]
If you find the database support relevant, please open a new issue to this. And we can discuss it there. Thanks

**Comment by thiagobustamante** [comment]
We are paving the way to implement this demand. The issue #15 was already commited. It added support to inject a middleware to handle the target destination for the proxy call.

It will allow load balance implementations, service discovery etc.

**Comment by thiagobustamante** [comment]
Implemented. Take a look at: https://github.com/Leanty/tree-gateway/wiki/loadBalancer. It will be available on next release
